#spring:
#  security:
#    user:
#      name: user
#      password: pass
#
#springdoc:
#  swagger-ui:
#    path: /sharepointapi
#
#sharepoint:
#  clientId: 3dd046e3-65dd-41e1-a266-f17f42535a64
#  clientSecret: 8a~8Q~V.L.ggxihTBlwgkjCYGqryIJmw4Ebn5aK_
#  tenantId: 02b87979-d129-41ba-a3df-f7e17e86c8ea
#  domain: malabarai
#  shared_folder: Shared Documents
#  site: /sites/raju-dev